- Name: English
  CanCheckerBeatQueen: 1
  CanQueenMoveOverMoreFields: 0
  ShouldCheckerMakeTheBestMoveFirst: 0
  CanCheckerMakeReverseBeat: 1
  ColorForTopLeftCorner: 1
  BoardSize: 8
  RowsWithCheckers: 0,1,2,5,6,7
  FieldsColors: Black
- Name: Italian
  CanCheckerBeatQueen: 0
  CanQueenMoveOverMoreFields: 0
  ShouldCheckerMakeTheBestMoveFirst: 1
  CanCheckerMakeReverseBeat: 1
  ColorForTopLeftCorner: 0
  BoardSize: 8
  RowsWithCheckers: 0,1,2,5,6,7
  FieldsColors: Black
- Name: Spanish
  CanCheckerBeatQueen: 1
  CanQueenMoveOverMoreFields: 1
  ShouldCheckerMakeTheBestMoveFirst: 1
  CanCheckerMakeReverseBeat: 0
  ColorForTopLeftCorner: 0
  BoardSize: 8
  RowsWithCheckers: 0,1,6,7
  FieldsColors: Black
- Name: German
  CanCheckerBeatQueen: 1
  CanQueenMoveOverMoreFields: 1
  ShouldCheckerMakeTheBestMoveFirst: 1
  CanCheckerMakeReverseBeat: 1
  ColorForTopLeftCorner: 0
  BoardSize: 8
  RowsWithCheckers: 0,1,2,5,6,7
  FieldsColors: Black
- Name: Russian
  CanCheckerBeatQueen: 1
  CanQueenMoveOverMoreFields: 1
  ShouldCheckerMakeTheBestMoveFirst: 0
  CanCheckerMakeReverseBeat: 1
  ColorForTopLeftCorner: 1
  BoardSize: 8
  RowsWithCheckers: 0,1,2,5,6,7
  FieldsColors: Black
- Name: Polish
  CanCheckerBeatQueen: 1
  CanQueenMoveOverMoreFields: 1
  ShouldCheckerMakeTheBestMoveFirst: 1
  CanCheckerMakeReverseBeat: 1
  ColorForTopLeftCorner: 0
  BoardSize: 10
  RowsWithCheckers: 0,1,2,3,6,7,8,9
  FieldsColors: Black
- Name: Canadian
  CanCheckerBeatQueen: 1
  CanQueenMoveOverMoreFields: 1
  ShouldCheckerMakeTheBestMoveFirst: 1
  CanCheckerMakeReverseBeat: 1
  ColorForTopLeftCorner: 0
  BoardSize: 12
  RowsWithCheckers: 0,1,2,3,4,7,8,9,10,11
  FieldsColors: Black
- Name: Turkish
  CanCheckerBeatQueen: 1
  CanQueenMoveOverMoreFields: 1
  ShouldCheckerMakeTheBestMoveFirst: 1
  CanCheckerMakeReverseBeat: 0
  ColorForTopLeftCorner: 1
  BoardSize: 8
  RowsWithCheckers: 1,2,5,6
  FieldsColors: White,Black