- Name: English
  CanCheckerBeatQueen: 1
  CanQueenMoveOverMoreFields: 0
  ShouldCheckerMakeTheBestMoveFirst: 0
  CanCheckerMakeReverseBeat: 1
  ColorForTopLeftCorner: 1
  BoardSize: 8
- Name: Italian
  CanCheckerBeatQueen: 0
  CanQueenMoveOverMoreFields: 0
  ShouldCheckerMakeTheBestMoveFirst: 1
  CanCheckerMakeReverseBeat: 1
  ColorForTopLeftCorner: 0
  BoardSize: 8
- Name: Spanish
  CanCheckerBeatQueen: 1
  CanQueenMoveOverMoreFields: 1
  ShouldCheckerMakeTheBestMoveFirst: 1
  CanCheckerMakeReverseBeat: 0
  ColorForTopLeftCorner: 0
  BoardSize: 8
- Name: German
  CanCheckerBeatQueen: 1
  CanQueenMoveOverMoreFields: 1
  ShouldCheckerMakeTheBestMoveFirst: 1
  CanCheckerMakeReverseBeat: 1
  ColorForTopLeftCorner: 0
  BoardSize: 8
- Name: Russian
  CanCheckerBeatQueen: 1
  CanQueenMoveOverMoreFields: 1
  ShouldCheckerMakeTheBestMoveFirst: 0
  CanCheckerMakeReverseBeat: 1
  ColorForTopLeftCorner: 1
  BoardSize: 8
- Name: Polish
  CanCheckerBeatQueen: 1
  CanQueenMoveOverMoreFields: 1
  ShouldCheckerMakeTheBestMoveFirst: 1
  CanCheckerMakeReverseBeat: 1
  ColorForTopLeftCorner: 0
  BoardSize: 10
- Name: Canadian
  CanCheckerBeatQueen: 1
  CanQueenMoveOverMoreFields: 1
  ShouldCheckerMakeTheBestMoveFirst: 1
  CanCheckerMakeReverseBeat: 1
  ColorForTopLeftCorner: 0
  BoardSize: 12
- Name: Turkish
  CanCheckerBeatQueen: 1
  CanQueenMoveOverMoreFields: 1
  ShouldCheckerMakeTheBestMoveFirst: 1
  CanCheckerMakeReverseBeat: 0
  ColorForTopLeftCorner: 1
  BoardSize: 8